server:
  port: 8889
spring:
  application:
    name: product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
mybatis:
  mapper-locations: classpath*:com/sell/mapper/*Mapper.xml
  type-aliases-package: com.sell.pojo
